### ISSUE TITLE
Backspace doesn't work

### ISSUE THREAD

**Issue by jimelrod** [neilsustc/vscode-markdown#17] opened 2017-07-17 18:18 UTC
Pressing the backspace key results in a warning... `warn: command 'markdown.extension.onBackspaceKey' not found` - and it doesn't backspace. See attached image.

![image](https://user-images.githubusercontent.com/1869729/28283146-70e748e6-6af2-11e7-90ff-74b4a6c49bbd.png)

**Comment by neilsustc** [comment] 2017-07-18 00:32
That's strange. I cannot reproduce.

![backspace](https://user-images.githubusercontent.com/7588612/28295484-730ae848-6b93-11e7-94c5-83514f304cd5.gif)

It seems that you have other markdown extensions installed. Could you please disable the other extensions and then test again.

**Comment by neilsustc** [comment] 2017-07-22 02:41
I bet this is also fixed in v0.7.7

**Closed** 2017-07-22 02:41 UTC
Labels: needs more info

**Comment by cgxeiji** [comment] 2017-12-20 05:31
I have found that this happens when pressing `F10`.
Pressing `F10` again solved the issue.

**Comment by neilsustc** [comment] 2017-12-20 05:57
🤔 still no idea about why

**Comment by cgxeiji** [comment] 2017-12-20 06:05
I was accidentally messing with the F# keys, but I am not sure which one triggered the error.

**Comment by neilsustc** [comment] 2018-01-25 00:36
🤣 Thanks for your report.

One common reason is that the extension requires some time to load when you open a Markdown file for the first time. For this case, wait 2 seconds after you open a md file.

Another possible reason is the extension files broken. Then you can try to reinstall the ext.

**Comment by borekb** [comment] 2018-01-28 18:48
Happening to me now. Sometimes, pressing Enter causes `command 'markdown.extension.onEnterKey' not found`, sometimes it just takes _very_ long to be executed (10-20 seconds).

I've tried waiting after VSCode fully loads and opening MD file only then, no help.

My installation:

- VSCode Version: Code 1.19.3 (7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba, 2018-01-25T10:36:43.673Z)
- OS Version: Windows_NT ia32 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
spellright|ban|2.1.10
emojisense|bie|0.3.0
markdown-preview-github-styles|bie|0.1.0
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-markdownlint|Dav|0.13.0
ghlink|dt|0.0.6
gitlens|eam|7.5.7
EditorConfig|Edi|0.12.0
tslint|eg2|1.0.24
vscode-npm-script|eg2|0.3.3
LogFileHighlighter|emi|1.2.0
auto-rename-tag|for|0.0.15
rest-client|hum|0.16.2
vscode-github|Kni|0.26.0
goto-last-edit-location|kri|0.2.1
git-tree-compare|let|1.1.4
terraform|mau|0.0.20
tgit-cmds|mbi|1.1.1
dotenv|mik|1.0.0
debugger-for-chrome|msj|4.1.0
vscode-docker|Pet|0.0.23
code-settings-sync|Sha|2.8.7
vscode-terminal-here|Tyr|0.1.1
es-quotes|vil|0.2.6
quokka-vscode|Wal|1.0.94
wallaby-vscode|Wal|1.0.75
local-history|xyz|1.6.2
markdown-all-in-one|yzh|1.0.3

**Comment by neilsustc** [comment] 2018-01-29 03:08
The extension is loaded when you open a MD file *the first time*.
So wait 2 seconds after opening a MD file (not after vscode launches).
I'm considering whether I need to add a status bar item to indicate that this extension is ready...

Do you see any error in the console (menubar>help>toggle developer tools)?

**Comment by borekb** [comment] 2018-01-29 07:20
Even when I open a MD file and wait for 10 seconds, the Enter key is extremely unresponsive (10-20 seconds reaction time). There are no errors in the dev tools related to this extension.

**Comment by borekb** [comment] 2018-01-29 07:29
I suspect it's some other extension; I've tried everything on a clean installation of VSCode Insiders with just this plugin installed and all is fine.

Any idea how to debug what could be competing for the Enter key?

**Comment by borekb** [comment] 2018-01-29 07:34
The issue seems to be happening with the [KnisterPeter/vscode-github](https://github.com/KnisterPeter/vscode-github) extension enabled, I'll post an issue there.

**Comment by neilsustc** [comment] 2018-01-29 07:36
I have an idea.
Open your extension folder (usually `C:\Users\[username]\.vscode-insiders\extensions`) with vscode
Use global search in the left activity bar
Find which `package.json` contains `"key": "enter"`

**Comment by autoferrit** [comment] 2018-02-23 17:08
so, i have this issue as well. removing this extension fixes the issue. i tried manually overriding the keymap to `Backspace` but didnt seem to change anything. it was already mapped. I looked for other extensions that use the backspace key as you mentioned, and only this extension seems to do that for me
```
❯ ag 'key": "enter' ~/.vscode-insiders/extensions                                                                                                                                                                                           
~/.vscode-insiders/extensions/yzhang.markdown-all-in-one-1.0.5/package.json
80:6:                           "key": "enter",            
1 matches                                                  
1 files contained matches                                  
4326 files searched                                        
21388767 bytes searched                                    
0.452680 seconds
```

**Comment by odelljl** [comment] 2018-03-07 23:40
I experience the problem with the backspace key upon upgrading to VS Code 1.21.0 (February).  I tried adding preference:
    "markdown.extension.onBackspaceKey": "Backspace"
But am warned that markdown.extension.onBackspaceKey is not a valid preference.

**Comment by neilsustc** [comment] 2018-03-08 02:02
You can find more details in #103

**Comment by VostokSisters** [comment] 2018-03-10 16:45
@neilsustc 

> You can find more details in #103 
It did not help me. These 4 files already have vscode.markdown-language-features

**Comment by neilsustc** [comment] 2018-03-11 03:52
Are you using the latest vscode (v1.21.0)?

**Comment by smilelight** [comment] 2018-03-13 04:21
You can just try right click and delete the key-bind~

**Comment by garyng** [comment] 2018-03-13 15:04
@smilelight Deleting the keybindings works for me.

**Comment by penut85420** [comment] 2018-03-29 08:32
@fvcproductions thx bro

**Comment by CarlitosDroid** [comment] 2018-06-24 19:34
Well, In my case I was using the 'Markdown All in One' extension, and I had the same problem, for instance an error as follows:
"command markdown onEnterKey not found"
I could solved it by reloading the extension, Go to Extension Tab and click on the  'Reload' blue button, but you could reinstall it again.
<img width="807" alt="screen shot 2018-06-24 at 2 30 03 pm" src="https://user-images.githubusercontent.com/10377529/41822837-7f4370c8-77bb-11e8-9337-a66b806ed721.png">

**Comment by psaren** [comment] 2018-10-15 16:10
I am experiencing the same problem，  this problem was solve when I reload Markdown All in One.

**Comment by gusbemacbe** [comment] 2019-04-18 07:59
I experience still this problem.

**Comment by yzhang-gh** [comment] 2019-04-18 08:09
This issue is too long ago. Feel free to open a new one (with some information).
